redis:
  image: redis:latest
  command: redis-server --appendonly yes

db:
  image: postgres:latest
  environment:
    POSTGRES_USER: freight
  env_file: .env

web:
  build: .
  links:
    - redis:redis
    - db:db
  environment:
    PYTHONUNBUFFERED: 1
    REDISCLOUD_URL: redis://redis:6379
    SQLALCHEMY_DATABASE_URI: postgresql://db/freight    
  env_file: .env
  ports:
    - 5000:5000
  volumes:
    - /root/.docker:/root/.docker
  command: bin/web --addr 0.0.0.0:5000

worker:
  build: .
  links:
    - redis:redis
    - db:db
  environment:
    PYTHONUNBUFFERED: 1
    REDISCLOUD_URL: redis://redis:6379
    SQLALCHEMY_DATABASE_URI: postgresql://db/freight
  env_file: .env
  volumes:
    - /root/.docker:/root/.docker
  command: bin/worker

